# Generated by Django 4.1.5 on 2023-01-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_daraja', '0002_auto_20181108_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=60)),
                ('session_id', models.CharField(max_length=60)),
            ],
        ),
    ]
