# Generated by Django 4.1.5 on 2023-01-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_daraja', '0003_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='service_code',
            field=models.CharField(default='*384*4421#', max_length=60),
        ),
        migrations.AddField(
            model_name='hero',
            name='text',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
