# Generated by Django 4.1.5 on 2023-01-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_daraja', '0004_hero_service_code_hero_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='service_code',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
