# Generated by Django 4.1.3 on 2023-01-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_daraja', '0007_rename_phone_number_hero_phonenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=60)),
                ('servicecode', models.CharField(max_length=60)),
                ('sessionid', models.CharField(max_length=60)),
                ('text', models.CharField(max_length=4)),
            ],
        ),
    ]
