# Generated by Django 4.1.3 on 2023-01-09 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_daraja', '0008_hro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hro',
            old_name='servicecode',
            new_name='serviceCode',
        ),
        migrations.RenameField(
            model_name='hro',
            old_name='sessionid',
            new_name='sessionID',
        ),
    ]
