# Generated by Django 4.1.3 on 2023-01-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_daraja', '0009_rename_servicecode_hro_servicecode_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
        migrations.AlterField(
            model_name='hro',
            name='text',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
