# Generated by Django 4.1.3 on 2023-01-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_daraja', '0011_alter_hro_phonenumber_alter_hro_servicecode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hro',
            name='text',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
