# Generated by Django 4.1.3 on 2023-01-12 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_daraja', '0012_alter_hro_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hro',
            old_name='phoneNumber',
            new_name='MSISDN',
        ),
        migrations.RenameField(
            model_name='hro',
            old_name='serviceCode',
            new_name='accessPoint',
        ),
        migrations.RenameField(
            model_name='hro',
            old_name='text',
            new_name='input',
        ),
    ]
